/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of the party account. Account can be to Provide support for services to other parties or to Service actual persons with services or products.. 
 */
export type AccountType = 'SERVICE' | 'SUPPORT';

export const AccountType = {
    SERVICE: 'SERVICE' as AccountType,
    SUPPORT: 'SUPPORT' as AccountType
};