/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressType } from './addressType';
import { AddressUse } from './addressUse';
import { Country } from './country';
import { Element } from './element';

/**
 * An address expressed using postal conventions (as opposed to GPS or other location definition formats). This data type may be used to convey addresses for use in delivering mail as well as for visiting locations which might not be valid for mail delivery. There are a variety of postal address formats defined around the world.  http://build.fhir.org//datatypes.html#Address 
 */
export interface Address { 
    /**
     * Guid of the structure
     */
    id: string;
    /**
     * This header of element with id and period of element activity.
     */
    header?: Element;
    /**
     * What address use for.
     */
    use?: AddressUse;
    /**
     * Type of address.
     */
    type?: AddressType;
    /**
     * Text representation of the address
     */
    text?: string;
    /**
     * Street name, number, direction & P.O. Box etc. This repeating element order: The order in which lines should appear in an address label
     */
    line?: Array<string>;
    /**
     * Name of city, town etc.
     */
    city?: string;
    /**
     * District name (aka county)
     */
    district?: string;
    /**
     * Address state. Sub-unit of country (abbreviations ok)
     */
    state?: string;
    /**
     * Postal code for area
     */
    postalCode?: string;
    /**
     * Country (e.g. can be ISO 3166 2 or 3 letter code)
     */
    country?: Country;
}