/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Element } from './element';
import { Locale } from './locale';

/**
 * This type is for containing or referencing attachments - additional data content defined in other formats. The most common use of this type is to include images or reports in some report format such as PDF. However it can be used for any data that has a MIME type.  http://build.fhir.org//datatypes.html#Attachment
 */
export interface Attachment { 
    /**
     * Guid of the attachmentt
     */
    id: string;
    /**
     * Management information for document
     */
    header?: Element;
    /**
     * Mime type of the content, with charset etc.
     */
    contentType?: string;
    /**
     * Format of the attached file.
     */
    fileFormat?: string;
    /**
     * Human language of the content (BCP-47)
     */
    language?: Locale;
    /**
     * Data inline, base64ed
     */
    data?: string;
    /**
     * Uri where the data can be found
     */
    url?: string;
    /**
     * Number of bytes of content (if url provided)
     */
    size?: any;
    /**
     * Hash of the data (sha-1, base64ed)
     */
    hash?: string;
    /**
     * Label to display in place of the data
     */
    title?: string;
    /**
     * Date attachment was first created
     */
    creation?: Date;
}