/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Specification for bank account transfer.
 */
export interface BankSpec { 
    /**
     * Routing number to institution.
     */
    routingNumber: string;
    /**
     * Account number of bank customer. 
     */
    accountNumber: string;
}