/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * https://www.hl7.org/fhir/v2/0116/index.html
 */
export type BedStatus = 'C' | 'H' | 'I' | 'K' | 'O' | 'U';

export const BedStatus = {
    C: 'C' as BedStatus,
    H: 'H' as BedStatus,
    I: 'I' as BedStatus,
    K: 'K' as BedStatus,
    O: 'O' as BedStatus,
    U: 'U' as BedStatus
};