/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { ContactPoint } from './contactPoint';
import { Element } from './element';
import { HumanName } from './humanName';

/**
 * Any record or information compiled or maintained with respect to a consumer that identifies the consumer and provides a means by which the consumer’s financial obligation incurred by accepting a free offer may be paid or otherwise satisfied, including but not limited to information pertaining to a consumer’s credit card, payment card, charge card, debit card, checking, savings, or other banking account, and electronic funds transfer information.
 */
export interface BillingInformation { 
    /**
     * Identity of category in the product line.
     */
    id: string;
    /**
     * This header of element with order and period of element activity.
     */
    header?: Element;
    /**
     * Billing address
     */
    address?: Address;
    /**
     * Name for billing information
     */
    name?: HumanName;
    /**
     * Phone for billing information
     */
    phone?: ContactPoint;
    /**
     * EMail for billing information
     */
    email?: ContactPoint;
}