/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BindingType } from './bindingType';
import { Identity } from './identity';

/**
 * Binding represents connection of entity to entity in other external systems. It can be system where entity actually originated ond from which it was imported or system where entity exported. 
 */
export interface Binding { 
    /**
     * Binding identity in system it imported from or exported to. Id is globally unique. Name is unique binding name inside entity only.
     */
    identity: Identity;
    /**
     * Type of binding defines system we bind to.
     */
    type: BindingType;
    /**
     * Code of object in system we bind to if different from id.
     */
    code?: string;
    /**
     * Any additional information that is necessary to get access or to operate with the binded object on other side
     */
    data?: string;
}