/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Contact type enumerator. Contact type specify what part of organization you contact.
 */
export type ContactType = 'ORG' | 'BILL' | 'ADMIN' | 'HR' | 'PAYOR' | 'PATINF' | 'PRESS';

export const ContactType = {
    ORG: 'ORG' as ContactType,
    BILL: 'BILL' as ContactType,
    ADMIN: 'ADMIN' as ContactType,
    HR: 'HR' as ContactType,
    PAYOR: 'PAYOR' as ContactType,
    PATINF: 'PATINF' as ContactType,
    PRESS: 'PRESS' as ContactType
};