/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Contact point system enumerator. All codes from system http://hl7.org/fhir/contact-point-system.
 */
export type ContactPointSystem = 'phone' | 'fax' | 'email' | 'pager' | 'url' | 'sms' | 'other';

export const ContactPointSystem = {
    Phone: 'phone' as ContactPointSystem,
    Fax: 'fax' as ContactPointSystem,
    Email: 'email' as ContactPointSystem,
    Pager: 'pager' as ContactPointSystem,
    Url: 'url' as ContactPointSystem,
    Sms: 'sms' as ContactPointSystem,
    Other: 'other' as ContactPointSystem
};