/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Period } from './period';

/**
 * The base definition for all elements contained inside a resource. All elements, whether defined as a Data Type (including primitives) or as part of a resource structure, have this base content:  Extensions An internal id There are 3 kinds of descendent types that specialize Element:  Primitive data types, that add a primitive value property of the specified type Complex data types, that add their own children (all of which are also elements) BackboneElement, A specialization that adds modifierExtension, which is the super-type of all the element types defined in resource definitions (e.g. Patient.contact) Note that resources themselves all specialize the base type Resource.  http://build.fhir.org//element.html
 */
export interface Element { 
    /**
     * Order of element in list. Order can be defined by user or selected by system. Most common order is order of introduction.
     */
    order?: number;
    /**
     * Rank of the element in list. 1 - is a highest rank.
     */
    rank?: number;
    /**
     * Time period element apply to. If period not close, it is current element. If period closed, it is element relevant for this period.
     */
    period?: Period;
}