/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Enumerator of the entity state.
 */
export type EntityState = 'DRAFT' | 'PENDING' | 'ACTIVE' | 'RETIRED' | 'ERROR';

export const EntityState = {
    DRAFT: 'DRAFT' as EntityState,
    PENDING: 'PENDING' as EntityState,
    ACTIVE: 'ACTIVE' as EntityState,
    RETIRED: 'RETIRED' as EntityState,
    ERROR: 'ERROR' as EntityState
};