/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * ISO/IEC 5218 Information technology. Codes for the representation of human sexes is an international standard that defines a representation of human sexes through a language-neutral single-digit code. It can be used in information systems such as database applications.
 */
export type Gender = 'MALE' | 'FEMALE' | 'NOT_APPLICABLE';

export const Gender = {
    MALE: 'MALE' as Gender,
    FEMALE: 'FEMALE' as Gender,
    NOTAPPLICABLE: 'NOT_APPLICABLE' as Gender
};