/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Completion } from './completion';

/**
 * Structure for object history. Object history provides information when object was updated and in what completion state it is now.
 */
export interface History { 
    /**
     * Date of object creation.
     */
    createdAt?: Date;
    /**
     * User created object.
     */
    createdBy?: string;
    /**
     * Date of object last update. This is important value as it is flag for optimistic commit to detect overriding changes. 
     */
    updatedAt: Date;
    /**
     * User last updated object.
     */
    updatedBy?: string;
    /**
     * Mote about goal of object update.
     */
    updatedNote?: string;
    /**
     * Message in issue associated with changes in object.
     */
    updatedMessage?: string;
    /**
     * Date object last update was reviewed by owner. This is indicates user see and aknowalage change.
     */
    reviewedAt?: Date;
    /**
     * User who reviewed and acknowledge the last update changes.
     */
    reviewedBy?: string;
    /**
     * Date object was retired.
     */
    retiredAt?: Date;
    /**
     * User retired object.
     */
    retiredBy?: string;
    /**
     * Array of completion statuses reached by this object.
     */
    completions?: Array<Completion>;
}