/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Element } from './element';
import { WeekDay } from './weekDay';

/**
 * What days/times during a week entity usually operational.
 */
export interface HoursOfOperation { 
    /**
     * Guid of the structure
     */
    id: string;
    /**
     * This header of element with id and period of element activity.
     */
    header?: Element;
    /**
     * Days of week entity is operational.
     */
    daysOfWeek?: Array<WeekDay>;
    /**
     * The entity is operational all day
     */
    allDay?: boolean;
    /**
     * Time that the entity operation start
     */
    openingTime?: any;
    /**
     * Time that the entity operation ends
     */
    closingTime?: any;
}