/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Element } from './element';
import { NameUse } from './nameUse';

/**
 * A name of a human with text, parts and usage information.  Names may be changed or repudiated. People may have different names in different contexts. Names may be divided into parts of different type that have variable significance depending on context, though the division into parts is not always significant. With personal names, the different parts might or might not be imbued with some implicit meaning; various cultures associate different importance with the name parts and the degree to which systems SHALL care about name parts around the world varies widely. 
 */
export interface HumanName { 
    /**
     * Guid of the structure
     */
    id: string;
    /**
     * This is header of name structure with id and period name element is active.
     */
    header?: Element;
    /**
     * Identifies the purpose for this name.
     */
    use?: NameUse;
    /**
     * Text representation of the full name.
     */
    text?: string;
    /**
     * Family name (often called 'Surname')
     */
    family?: string;
    /**
     * Given names (not always 'first'). Includes middle names This repeating element order: Given Names appear in the correct order for presenting the name
     */
    given?: Array<string>;
    /**
     * Parts that come before the name This repeating element order: Prefixes appear in the correct order for presenting the name
     */
    prefix?: Array<string>;
    /**
     * Parts that come after the name This repeating element order: Suffixes appear in the correct order for presenting the name
     */
    suffix?: Array<string>;
}