/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Identity of object in DifHub. Objects can be identify by globaly unique Id and localy unique name.
 */
export interface Identity { 
    /**
     * Id of the object. It is global unique identificator, optional for minor objects and required for major objects. When object created Id will be generated by backend service.
     */
    id?: string;
    /**
     * Name of the object. It is textual object identificator, need to be unique inside folder of the object.
     */
    name?: string;
    /**
     * Description for the object functionality. It is text with specification of object and way it used in application.
     */
    description?: string;
}