/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Identifier type enumerator. A coded type for an identifier that can be used to determine which identifier to use for a specific purpose.Include these codes as defined in http://terminology.hl7.org/CodeSystem/v2-0203.
 */
export type IdentifierType = 'DL' | 'PPN' | 'BRN' | 'MR' | 'MCN' | 'EN' | 'TAX' | 'NIIP' | 'PRN' | 'MD' | 'DR' | 'ACSN' | 'UDI' | 'SNO' | 'SB' | 'PLAC' | 'FILL' | 'JHN';

export const IdentifierType = {
    DL: 'DL' as IdentifierType,
    PPN: 'PPN' as IdentifierType,
    BRN: 'BRN' as IdentifierType,
    MR: 'MR' as IdentifierType,
    MCN: 'MCN' as IdentifierType,
    EN: 'EN' as IdentifierType,
    TAX: 'TAX' as IdentifierType,
    NIIP: 'NIIP' as IdentifierType,
    PRN: 'PRN' as IdentifierType,
    MD: 'MD' as IdentifierType,
    DR: 'DR' as IdentifierType,
    ACSN: 'ACSN' as IdentifierType,
    UDI: 'UDI' as IdentifierType,
    SNO: 'SNO' as IdentifierType,
    SB: 'SB' as IdentifierType,
    PLAC: 'PLAC' as IdentifierType,
    FILL: 'FILL' as IdentifierType,
    JHN: 'JHN' as IdentifierType
};