/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attachment } from './attachment';
import { Element } from './element';
import { IdentifierType } from './identifierType';
import { IdentifierUse } from './identifierUse';
import { ReferenceIdentity } from './referenceIdentity';

/**
 * A numeric or alphanumeric string that is associated with a single object or entity within a given system. Typically, identifiers are used to connect content in resources to external content available in other frameworks or protocols. Identifiers are associated with objects and may be changed or retired due to human or system process and errors.  Structure
 */
export interface Identifier { 
    /**
     * Guid of the structure
     */
    id: string;
    /**
     * This is header of identifier element with  id and period element is active.
     */
    header?: Element;
    /**
     * A numeric or alphanumeric string that is associated with a single object or entity within a given system. Typically, identifiers are used to connect content in resources to external content available in other frameworks or protocols. Identifiers are associated with objects and may be changed or retired due to human or system process and errors.  
     */
    use?: IdentifierUse;
    /**
     * Description of identifier
     */
    type?: IdentifierType;
    /**
     * The namespace for the identifier value.
     */
    system?: string;
    /**
     * The value that is unique.
     */
    value?: string;
    /**
     * Description of identifier. Provide additional information about identifier.
     */
    description?: string;
    /**
     * Organization that issued id (may be just text)
     */
    assigner?: ReferenceIdentity;
    /**
     * Image or copy of the document to support identifier.
     */
    attachment?: Array<Attachment>;
}