/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Identifier use enumerator. All codes from system http://hl7.org/fhir/identifier-use.
 */
export type IdentifierUse = 'usual' | 'official' | 'temp' | 'secondary' | 'old';

export const IdentifierUse = {
    Usual: 'usual' as IdentifierUse,
    Official: 'official' as IdentifierUse,
    Temp: 'temp' as IdentifierUse,
    Secondary: 'secondary' as IdentifierUse,
    Old: 'old' as IdentifierUse
};