/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of legal entity. Legal entity can represent Person or Business.
 */
export type LegalEntityType = 'PERSONAL' | 'BUSINESS';

export const LegalEntityType = {
    PERSONAL: 'PERSONAL' as LegalEntityType,
    BUSINESS: 'BUSINESS' as LegalEntityType
};