/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Country } from './country';
import { Entity } from './entity';
import { Identity } from './identity';
import { LegalEntityType } from './legalEntityType';
import { Period } from './period';

/**
 * Legal entity of a party. Party can have multiple legal entities used in different regions or for any other reason.
 */
export interface LegalEntity { 
    /**
     * Identity of the legal entity used in services and UI. Name used for URI of Legal Entity inside Party.
     */
    identity: Identity;
    /**
     * Legal Entity is a resource entity and have API access. Parent for legal entity referenced to Party. 
     */
    entity: Entity;
    /**
     * Type of legal entity
     */
    type: LegalEntityType;
    /**
     * Region for legal entity.
     */
    country?: Country;
    /**
     * Human friendly legal entity name used on documents when different from actual legal name.
     */
    legalEntityCode?: string;
    /**
     * Id provided by respective government for legal entity.
     */
    govermentId?: string;
    /**
     * Date legal entity start and end time to operate.
     */
    active?: Period;
}