/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This value set includes codes from the following code systems:  Include all codes defined in http://hl7.org/fhir/location-mode
 */
export type LocationMode = 'instance' | 'kind';

export const LocationMode = {
    Instance: 'instance' as LocationMode,
    Kind: 'kind' as LocationMode
};