/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { BedStatus } from './bedStatus';
import { ContactPoint } from './contactPoint';
import { Entity } from './entity';
import { HoursOfOperation } from './hoursOfOperation';
import { Identity } from './identity';
import { LocationMode } from './locationMode';
import { LocationStatus } from './locationStatus';
import { LocationType } from './locationType';
import { Position } from './position';
import { ServiceDeliveryLocationRoleType } from './serviceDeliveryLocationRoleType';

/**
 * https://www.hl7.org/fhir/location.html Details and position information for a physical place where services are provided and resources and participants may be stored, found, contained, or accommodated.  A Location includes both incidental locations (a place which is used for healthcare without prior designation or authorization) and dedicated, formally appointed locations. Locations may be private, public, mobile or fixed and scale from small freezers to full hospital buildings or parking garages.
 */
export interface Location { 
    /**
     * Location identity. Id is global (guid), Name is location definition and it is not unique.
     */
    identity: Identity;
    /**
     * Location is an entity and can be created and updated through API.
     */
    entity?: Entity;
    /**
     * Type of location.
     */
    type?: Array<ServiceDeliveryLocationRoleType>;
    /**
     * Mode of location.
     */
    mode?: LocationMode;
    /**
     * Status of location.
     */
    status?: LocationStatus;
    /**
     * The operational status of the location (typically only for a bed/room)
     */
    operationalStatus?: BedStatus;
    /**
     * Physical form of the location
     */
    physicalType?: LocationType;
    /**
     * A contact detail.
     */
    telecom?: Array<ContactPoint>;
    /**
     * One or more addresses for the contact.
     */
    address?: Address;
    /**
     * The absolute geographic location
     */
    position?: Position;
    /**
     * What days/times during a week is this location usually open
     */
    hoursOfOperation?: Array<HoursOfOperation>;
    /**
     * Description of availability exceptions
     */
    availabilityExceptions?: string;
    /**
     * Another Location this one is physically a part of
     */
    partOf?: string;
}