/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This value set includes codes from the following code systems:  Include all codes defined in http://hl7.org/fhir/location-status
 */
export type LocationStatus = 'active' | 'suspended' | 'inactive';

export const LocationStatus = {
    Active: 'active' as LocationStatus,
    Suspended: 'suspended' as LocationStatus,
    Inactive: 'inactive' as LocationStatus
};