/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * https://www.hl7.org/fhir/valueset-location-physical-type.html
 */
export type LocationType = 'si' | 'bu' | 'wi' | 'wa' | 'lvl' | 'co' | 'ro' | 'bd' | 've' | 'ho' | 'ca' | 'rd' | 'area' | 'jdn';

export const LocationType = {
    Si: 'si' as LocationType,
    Bu: 'bu' as LocationType,
    Wi: 'wi' as LocationType,
    Wa: 'wa' as LocationType,
    Lvl: 'lvl' as LocationType,
    Co: 'co' as LocationType,
    Ro: 'ro' as LocationType,
    Bd: 'bd' as LocationType,
    Ve: 've' as LocationType,
    Ho: 'ho' as LocationType,
    Ca: 'ca' as LocationType,
    Rd: 'rd' as LocationType,
    Area: 'area' as LocationType,
    Jdn: 'jdn' as LocationType
};