/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of party participated in the Network. Party can be Person, Medical Clinic or Service Provider.
 */
export type PartyType = 'PERSON' | 'CLINIC' | 'PROVIDER';

export const PartyType = {
    PERSON: 'PERSON' as PartyType,
    CLINIC: 'CLINIC' as PartyType,
    PROVIDER: 'PROVIDER' as PartyType
};