/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankSpec } from './bankSpec';
import { CardSpec } from './cardSpec';

/**
 * Payment specification for all supported payment types.
 */
export interface PaymentInstrumentSpec { 
    /**
     * Specification for bank account as payment instrument.
     */
    bank?: BankSpec;
    /**
     * Specification for credit card as payment instrument.
     */
    card?: CardSpec;
}