/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Element } from './element';
import { PaymentInstrumentSpec } from './paymentInstrumentSpec';
import { PaymentInstrumentType } from './paymentInstrumentType';

/**
 * Payment instrument to use for payment from eccount.
 */
export interface PaymentInstrument { 
    /**
     * Identity of category in the product line.
     */
    id: string;
    /**
     * This header of element with order and period of element activity.
     */
    header?: Element;
    /**
     * Type of financial instrument used for account payments.
     */
    type?: PaymentInstrumentType;
    /**
     * Name of payment instrument for user to identify it
     */
    name?: string;
    /**
     * Specification of payment instrument for specified type.
     */
    spec?: PaymentInstrumentSpec;
}