/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of the payment instrument.  
 */
export type PaymentInstrumentType = 'CASH' | 'CARD' | 'CHECK' | 'TRANSFER' | 'WALLET' | 'NETWORK' | 'CRYPTOCURRENCY';

export const PaymentInstrumentType = {
    CASH: 'CASH' as PaymentInstrumentType,
    CARD: 'CARD' as PaymentInstrumentType,
    CHECK: 'CHECK' as PaymentInstrumentType,
    TRANSFER: 'TRANSFER' as PaymentInstrumentType,
    WALLET: 'WALLET' as PaymentInstrumentType,
    NETWORK: 'NETWORK' as PaymentInstrumentType,
    CRYPTOCURRENCY: 'CRYPTOCURRENCY' as PaymentInstrumentType
};