/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A time period defined by a start and end date/time.  A period specifies a range of times. The context of use will specify whether the entire range applies (e.g. \"the patient was an inpatient of the hospital for this time range\") or one value from the period applies (e.g. \"give to the patient between 2 and 4 pm on 24-Jun 2013\"). This is simple period used not as part of array of elements.
 */
export interface Period { 
    /**
     * Starting time with inclusive boundary
     */
    start?: Date;
    /**
     * End time with inclusive boundary, if not ongoing.
     */
    end?: Date;
}