/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The absolute geographic location.
 */
export interface Position { 
    /**
     * Longitude with WGS84 datum
     */
    longitude?: any;
    /**
     * Latitude with WGS84 datum
     */
    altitude?: any;
    /**
     * Altitude with WGS84 datum
     */
    latitude?: any;
}