/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Complex structure to describe referenced resource
 */
export interface ReferenceIdentity { 
    /**
     * Optional URI of the target Resource
     */
    id?: string;
    /**
     * Optional URI of the target Resource
     */
    resourceId?: string;
    /**
     * Optional URI of the target Resource
     */
    name?: string;
    /**
     * Description of the Reference, can be target Resource description or custom one
     */
    description?: string;
    /**
     * Optional URI of the target Resource
     */
    type?: string;
    /**
     * Optional URI of the target Resource
     */
    uri?: string;
}