/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This is list of regions used by Network to operate.
 */
export type Region = 'US-WEST-2' | 'US-EAST-2';

export const Region = {
    WEST2: 'US-WEST-2' as Region,
    EAST2: 'US-EAST-2' as Region
};