/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { ContactPoint } from './contactPoint';
import { Element } from './element';
import { HumanName } from './humanName';

/**
 * Customs inspection is an important procedure during transportation. Normally, after the parcel arrived in the destination country/area, it will go through the course of customs inspection. If the status of the parcel has not been updated for a long time, based on the tracking info, the addressee should either contact the seller for the necessary document/paper needed by the customs or contact the local customs to assist in customs clearance. For your information, if the shipments sent to most European countries are held by the customs, it is suggested that the addressee can get back to the seller to ask for some kind of invoice or a description of the parcel for the customs. If the parcel is not claimed for a long time, the parcel will be then destroyed. So please pay attention to the deadline. Below please kindly check the common customs information.
 */
export interface ShippingInformation { 
    /**
     * Identity of category in the product line.
     */
    id: string;
    /**
     * This header of element with order and period of element activity.
     */
    header?: Element;
    address?: Address;
    name?: HumanName;
    phone?: ContactPoint;
    email?: ContactPoint;
    /**
     * Instructions for delivery
     */
    deliveryInstructions?: string;
}