/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Element } from './element';

/**
 * Flag that indicates if terms and conditions are accepted
 */
export interface TermsAndConditions { 
    /**
     * Guid of the structure
     */
    id: string;
    /**
     * This header of element with id and period of element activity.
     */
    header?: Element;
    /**
     * Boolean value indicating if terms and conditions are accepted
     */
    isSet?: boolean;
    /**
     * Text describing terms and conditions
     */
    termsAndConditionsText?: string;
    /**
     * Version of terms and conditions
     */
    version?: any;
}