/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmailAddress } from './emailAddress';
import { Entity } from './entity';
import { Identity } from './identity';
import { ReferenceIdentity } from './referenceIdentity';
import { TermsAndConditions } from './termsAndConditions';
import { UserPhone } from './userPhone';

/**
 * Complete information about user.
 */
export interface User { 
    /**
     * User identity. Id is user global id (guid), Name is user email, description - used for user resume.
     */
    identity: Identity;
    /**
     * User is an entity/resource and can be created and updated through RESTful API.
     */
    entity?: Entity;
    /**
     * email used for user communication.
     */
    email: EmailAddress;
    /**
     * Phone used for user registration and authentication.
     */
    phone?: UserPhone;
    /**
     * User public profile. Profile contains public information about user. This information will be visible to other users of organization. Additional profiles can be used in specific organization to override elements of profile different for this organization.
     */
    profile?: string;
    /**
     * List of parties that the user owns
     */
    parties?: Array<string>;
    /**
     * Primary Party. Assigned while user creation in the system. 
     */
    primaryParty?: string;
    /**
     * Reference identity of authorization provider
     */
    provider?: ReferenceIdentity;
    /**
     * List of terms and conditions contracts
     */
    termsAndConditions?: Array<TermsAndConditions>;
}