/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Enumerator Names of the days of the weeks by ISO 8601 and RFC 3339.
 */
export type WeekDay = 'MONDAY' | 'TUESDAT' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';

export const WeekDay = {
    MONDAY: 'MONDAY' as WeekDay,
    TUESDAT: 'TUESDAT' as WeekDay,
    WEDNESDAY: 'WEDNESDAY' as WeekDay,
    THURSDAY: 'THURSDAY' as WeekDay,
    FRIDAY: 'FRIDAY' as WeekDay,
    SATURDAY: 'SATURDAY' as WeekDay,
    SUNDAY: 'SUNDAY' as WeekDay
};