export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './locations.service';
import { LocationsService } from './locations.service';
export * from './parties.service';
import { PartiesService } from './parties.service';
export * from './partyAccounts.service';
import { PartyAccountsService } from './partyAccounts.service';
export * from './partyContacts.service';
import { PartyContactsService } from './partyContacts.service';
export * from './partyLegalEntities.service';
import { PartyLegalEntitiesService } from './partyLegalEntities.service';
export * from './partyLocations.service';
import { PartyLocationsService } from './partyLocations.service';
export * from './partyPersons.service';
import { PartyPersonsService } from './partyPersons.service';
export * from './persons.service';
import { PersonsService } from './persons.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [ContactsService, LocationsService, PartiesService, PartyAccountsService, PartyContactsService, PartyLegalEntitiesService, PartyLocationsService, PartyPersonsService, PersonsService, UsersService];
