/**
 * User API
 * User application provides support for most basic functionalities. Most important to keep private user information to allow identify the user and maintain contact information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Person } from '../model/person';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PartyPersonsService {

    protected basePath = 'http://localhost:8090';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * CreatePerson
     * Create new Person. Validate Person not yet exist.
     * @param xEntityPartyId Party folder maintained by.
     * @param partyId Party Id to fetch and put records
     * @param body Person data specification for update.
     * @param bearer JWT Bearer token
     * @param xAccessReference Reference to resource/file which contains access details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public partyPersonsCreatePerson(xEntityPartyId: string, partyId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public partyPersonsCreatePerson(xEntityPartyId: string, partyId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public partyPersonsCreatePerson(xEntityPartyId: string, partyId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public partyPersonsCreatePerson(xEntityPartyId: string, partyId: string, body?: Person, bearer?: string, xAccessReference?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (xEntityPartyId === null || xEntityPartyId === undefined) {
            throw new Error('Required parameter xEntityPartyId was null or undefined when calling partyPersonsCreatePerson.');
        }

        if (partyId === null || partyId === undefined) {
            throw new Error('Required parameter partyId was null or undefined when calling partyPersonsCreatePerson.');
        }




        let headers = this.defaultHeaders;
        if (bearer !== undefined && bearer !== null) {
            headers = headers.set('bearer', String(bearer));
        }
        if (xEntityPartyId !== undefined && xEntityPartyId !== null) {
            headers = headers.set('X-entity-partyId', String(xEntityPartyId));
        }
        if (xAccessReference !== undefined && xAccessReference !== null) {
            headers = headers.set('X-access-reference', String(xAccessReference));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/parties/${encodeURIComponent(String(partyId))}/persons`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * GetPerson
     * Get person or list of persons from service.
     * @param partyId Party Id to fetch and put records
     * @param personId Person Id to fetch and put records
     * @param xEntityPartyId Party folder maintained by.
     * @param bearer JWT Bearer token
     * @param options Options specified additional requirements for returned entity. For example reconcile option will require to send events to data lake and mark as reconciliation. 
     * @param startTime Beginning of time window specified to limit objects with last updated in this time window.
     * @param endTime End of time window specified to limit objects with last updated in this time window.
     * @param xAccessReference Reference to resource/file which contains access details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public partyPersonsGetPerson(partyId: string, personId: string, xEntityPartyId: string, bearer?: string, options?: string, startTime?: any, endTime?: any, xAccessReference?: string, observe?: 'body', reportProgress?: boolean): Observable<Person>;
    public partyPersonsGetPerson(partyId: string, personId: string, xEntityPartyId: string, bearer?: string, options?: string, startTime?: any, endTime?: any, xAccessReference?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Person>>;
    public partyPersonsGetPerson(partyId: string, personId: string, xEntityPartyId: string, bearer?: string, options?: string, startTime?: any, endTime?: any, xAccessReference?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Person>>;
    public partyPersonsGetPerson(partyId: string, personId: string, xEntityPartyId: string, bearer?: string, options?: string, startTime?: any, endTime?: any, xAccessReference?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (partyId === null || partyId === undefined) {
            throw new Error('Required parameter partyId was null or undefined when calling partyPersonsGetPerson.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling partyPersonsGetPerson.');
        }

        if (xEntityPartyId === null || xEntityPartyId === undefined) {
            throw new Error('Required parameter xEntityPartyId was null or undefined when calling partyPersonsGetPerson.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (options !== undefined && options !== null) {
            queryParameters = queryParameters.set('options', <any>options);
        }
        if (startTime !== undefined && startTime !== null) {
            queryParameters = queryParameters.set('startTime', <any>startTime);
        }
        if (endTime !== undefined && endTime !== null) {
            queryParameters = queryParameters.set('endTime', <any>endTime);
        }

        let headers = this.defaultHeaders;
        if (bearer !== undefined && bearer !== null) {
            headers = headers.set('bearer', String(bearer));
        }
        if (xEntityPartyId !== undefined && xEntityPartyId !== null) {
            headers = headers.set('X-entity-partyId', String(xEntityPartyId));
        }
        if (xAccessReference !== undefined && xAccessReference !== null) {
            headers = headers.set('X-access-reference', String(xAccessReference));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Person>('get',`${this.basePath}/parties/${encodeURIComponent(String(partyId))}/persons/${encodeURIComponent(String(personId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * GetPersonList
     * Get person or list of persons from service.
     * @param partyId Party Id to fetch and put records
     * @param xEntityPartyId Party folder maintained by.
     * @param bearer JWT Bearer token
     * @param options Options specified additional requirements for returned entity. For example reconcile option will require to send events to data lake and mark as reconciliation. 
     * @param startTime Beginning of time window specified to limit objects with last updated in this time window.
     * @param endTime End of time window specified to limit objects with last updated in this time window.
     * @param search Expression to limit number of entities in response.
     * @param xAccessReference Reference to resource/file which contains access details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public partyPersonsGetPersonList(partyId: string, xEntityPartyId: string, bearer?: string, options?: string, startTime?: any, endTime?: any, search?: string, xAccessReference?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Person>>;
    public partyPersonsGetPersonList(partyId: string, xEntityPartyId: string, bearer?: string, options?: string, startTime?: any, endTime?: any, search?: string, xAccessReference?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Person>>>;
    public partyPersonsGetPersonList(partyId: string, xEntityPartyId: string, bearer?: string, options?: string, startTime?: any, endTime?: any, search?: string, xAccessReference?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Person>>>;
    public partyPersonsGetPersonList(partyId: string, xEntityPartyId: string, bearer?: string, options?: string, startTime?: any, endTime?: any, search?: string, xAccessReference?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (partyId === null || partyId === undefined) {
            throw new Error('Required parameter partyId was null or undefined when calling partyPersonsGetPersonList.');
        }

        if (xEntityPartyId === null || xEntityPartyId === undefined) {
            throw new Error('Required parameter xEntityPartyId was null or undefined when calling partyPersonsGetPersonList.');
        }







        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (options !== undefined && options !== null) {
            queryParameters = queryParameters.set('options', <any>options);
        }
        if (startTime !== undefined && startTime !== null) {
            queryParameters = queryParameters.set('startTime', <any>startTime);
        }
        if (endTime !== undefined && endTime !== null) {
            queryParameters = queryParameters.set('endTime', <any>endTime);
        }
        if (search !== undefined && search !== null) {
            queryParameters = queryParameters.set('search', <any>search);
        }

        let headers = this.defaultHeaders;
        if (bearer !== undefined && bearer !== null) {
            headers = headers.set('bearer', String(bearer));
        }
        if (xEntityPartyId !== undefined && xEntityPartyId !== null) {
            headers = headers.set('X-entity-partyId', String(xEntityPartyId));
        }
        if (xAccessReference !== undefined && xAccessReference !== null) {
            headers = headers.set('X-access-reference', String(xAccessReference));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Person>>('get',`${this.basePath}/parties/${encodeURIComponent(String(partyId))}/persons`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * ModifyPerson
     * Change Person properties to values specified in request. Property not specified will remain same. No element of any collection will be deleted. 
     * @param xEntityPartyId Party folder maintained by.
     * @param partyId Party Id to fetch and put records
     * @param personId Person Id to fetch and put records
     * @param body Person data specification for update.
     * @param bearer JWT Bearer token
     * @param xAccessReference Reference to resource/file which contains access details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public partyPersonsModifyPerson(xEntityPartyId: string, partyId: string, personId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public partyPersonsModifyPerson(xEntityPartyId: string, partyId: string, personId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public partyPersonsModifyPerson(xEntityPartyId: string, partyId: string, personId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public partyPersonsModifyPerson(xEntityPartyId: string, partyId: string, personId: string, body?: Person, bearer?: string, xAccessReference?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (xEntityPartyId === null || xEntityPartyId === undefined) {
            throw new Error('Required parameter xEntityPartyId was null or undefined when calling partyPersonsModifyPerson.');
        }

        if (partyId === null || partyId === undefined) {
            throw new Error('Required parameter partyId was null or undefined when calling partyPersonsModifyPerson.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling partyPersonsModifyPerson.');
        }




        let headers = this.defaultHeaders;
        if (bearer !== undefined && bearer !== null) {
            headers = headers.set('bearer', String(bearer));
        }
        if (xEntityPartyId !== undefined && xEntityPartyId !== null) {
            headers = headers.set('X-entity-partyId', String(xEntityPartyId));
        }
        if (xAccessReference !== undefined && xAccessReference !== null) {
            headers = headers.set('X-access-reference', String(xAccessReference));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('patch',`${this.basePath}/parties/${encodeURIComponent(String(partyId))}/persons/${encodeURIComponent(String(personId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * UpdatePerson
     * Change person specification. Person will be created if not exist.
     * @param xEntityPartyId Party folder maintained by.
     * @param partyId Party Id to fetch and put records
     * @param personId Person Id to fetch and put records
     * @param body Person data specification for update.
     * @param bearer JWT Bearer token
     * @param xAccessReference Reference to resource/file which contains access details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public partyPersonsUpdatePerson(xEntityPartyId: string, partyId: string, personId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public partyPersonsUpdatePerson(xEntityPartyId: string, partyId: string, personId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public partyPersonsUpdatePerson(xEntityPartyId: string, partyId: string, personId: string, body?: Person, bearer?: string, xAccessReference?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public partyPersonsUpdatePerson(xEntityPartyId: string, partyId: string, personId: string, body?: Person, bearer?: string, xAccessReference?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (xEntityPartyId === null || xEntityPartyId === undefined) {
            throw new Error('Required parameter xEntityPartyId was null or undefined when calling partyPersonsUpdatePerson.');
        }

        if (partyId === null || partyId === undefined) {
            throw new Error('Required parameter partyId was null or undefined when calling partyPersonsUpdatePerson.');
        }

        if (personId === null || personId === undefined) {
            throw new Error('Required parameter personId was null or undefined when calling partyPersonsUpdatePerson.');
        }




        let headers = this.defaultHeaders;
        if (bearer !== undefined && bearer !== null) {
            headers = headers.set('bearer', String(bearer));
        }
        if (xEntityPartyId !== undefined && xEntityPartyId !== null) {
            headers = headers.set('X-entity-partyId', String(xEntityPartyId));
        }
        if (xAccessReference !== undefined && xAccessReference !== null) {
            headers = headers.set('X-access-reference', String(xAccessReference));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/parties/${encodeURIComponent(String(partyId))}/persons/${encodeURIComponent(String(personId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
